# Generated by Django 3.2.4 on 2022-06-14 14:55

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Director'), (2, 'Accounter'), (3, 'Manager'), (4, 'Sotuvchi'), (5, 'Qoravul'), (6, 'Omborchi asosiy'), (7, 'Tarozi_hisobchi bon'), (8, 'Tarozi_hisobchi Xisobchi'), (9, 'Tarozi_hisobchi Moliyachi'), (10, 'Texnolog'), (11, 'Omborchi filial'), (12, 'Kassir'), (13, 'Yem Production'), (14, 'Un Production'), (15, 'Yem Ombor'), (16, 'Un Ombor'), (17, 'Sotuv rahbari'), (18, 'Operator'), (19, 'Ombor kassir'), (20, 'Qoravul + Asosiy Ombor'), (21, 'Yordamchi bugalter'), (22, 'Hujjatchi'), (23, 'Zavod Direktori')], default=0)),
                ('order_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('firebase_token', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishchilar',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AktUnOutlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('1', "To'lanmagan"), ('2', "To'langan")], default=1, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AktUnWagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('brutto_akt', models.IntegerField(default=0)),
                ('tara_akt', models.IntegerField(default=0)),
                ('netto_akt', models.IntegerField(default=0)),
                ('brutto_fakt', models.IntegerField(default=0)),
                ('tara_fakt', models.IntegerField(default=0)),
                ('netto_fakt', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Akt Un Wagon',
                'verbose_name_plural': 'Akts Un Wagonlar',
            },
        ),
        migrations.CreateModel(
            name='BankShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_sum', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('shot_numbers', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bank hisob raqamlar',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdori', models.FloatField(default=0)),
                ('hajmi', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('is_edited', models.BooleanField(default=False)),
                ('load', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Savatcha',
                'verbose_name_plural': 'Savatchalar',
            },
        ),
        migrations.CreateModel(
            name='BasketQaytuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdori', models.FloatField(default=0)),
                ('hajmi', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('is_edited', models.BooleanField(default=False)),
                ('load', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bunker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fakt_neto', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bunker',
                'verbose_name_plural': 'Bunkerlar',
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('naqd_pull_sum', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('naqd_pull_dollor', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kassa',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CheckClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField()),
                ('normal', models.IntegerField()),
                ('passive', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckCustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urtacha', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChiqimCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Chiqim Category',
            },
        ),
        migrations.CreateModel(
            name='ChiqimSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chiqimcategory')),
            ],
            options={
                'verbose_name_plural': 'Chiqim Sub-Category',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compony', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
            ],
            options={
                'verbose_name': 'Klint',
                'verbose_name_plural': 'Klintlar',
            },
        ),
        migrations.CreateModel(
            name='ClientTin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compony', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('date_start', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Qob klinti',
                'verbose_name_plural': 'Qob klintilar',
            },
        ),
        migrations.CreateModel(
            name='ClientUn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compony', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('date_start', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Un klinti',
                'verbose_name_plural': 'Un klintilar',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sotish_sum', models.IntegerField()),
                ('olish_sum', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('debt_uz', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('debt_kz', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('hudud', models.IntegerField(choices=[(1, 'Samarqand'), (2, 'Toshkent'), (3, 'Jizzax'), (4, "Afg'on"), (5, 'Navoiy'), (6, 'Qashqadaryo'), (7, 'Surxondaryo'), (8, 'Qoraqalpogiston'), (9, 'Andijon'), (10, 'Buxoro'), (11, 'Fargona'), (12, 'Xorazm'), (13, 'Namangan'), (14, 'Sirdaryo')], default=1)),
                ('phone', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('extra_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_number', models.IntegerField(blank=True, default=0, null=True)),
                ('inn', models.IntegerField(blank=True, default=0, null=True)),
                ('mfo', models.IntegerField(blank=True, default=0, null=True)),
                ('limit', models.IntegerField(blank=True, default=0, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Faol'), (2, 'Kamroq tovar oluvchilar '), (3, 'Ishlamay qolgan mijozlar ')], default=1)),
                ('status_turi', models.IntegerField(choices=[(1, 'Kup miqdorda, kam oladi'), (2, 'Kam miqdorda, kup oladi')], default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.category')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
            },
        ),
        migrations.CreateModel(
            name='OmborCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('naqd_pull_sum', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('naqd_pull_dollor', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ombor Kassasi',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('update_date', models.DateField(default=django.utils.timezone.now)),
                ('summa_total', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('summa_total_pay', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'In process'), ('3', 'Process done'), ('4', 'Finished'), ('5', 'Rejected')], default=1, max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='Sended orders/')),
                ('car_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('type_bonus', models.CharField(blank=True, choices=[('1', 'Percent'), ('2', 'Dollar')], max_length=255, null=True)),
                ('bonus', models.IntegerField(default=0)),
                ('payment_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('turned_date', models.DateTimeField(blank=True, null=True)),
                ('entered_date', models.DateTimeField(blank=True, null=True)),
                ('left_date', models.DateTimeField(blank=True, null=True)),
                ('baskets', models.ManyToManyField(related_name='orderlar', to='home.Basket')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderlar', to='home.customer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField(blank=True, default=1, help_text='50kg = 1qob', null=True)),
                ('type_country', models.IntegerField(blank=True, choices=[(1, 'uz'), (2, 'kz')], default=1, null=True)),
                ('pr_code', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Maxsulot',
                'verbose_name_plural': 'Maxsulotlar',
            },
        ),
        migrations.CreateModel(
            name='QozoqCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('naqd_pull_sum', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('naqd_pull_dollor', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Qozoq Kassa',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('akb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receipt_for_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hudud', models.IntegerField(choices=[(1, 'Samarqand'), (2, 'Toshkent'), (3, 'Jizzax'), (4, "Afg'on"), (5, 'Navoiy'), (6, 'Qashqadaryo'), (7, 'Surxondaryo'), (8, 'Qoraqalpogiston'), (9, 'Andijon'), (10, 'Buxoro'), (11, 'Fargona'), (12, 'Xorazm'), (13, 'Namangan'), (14, 'Sirdaryo')], default=1)),
                ('month', models.IntegerField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SecondCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('naqd_pull_sum', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('naqd_pull_dollor', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ikkkinchi Kassa',
            },
        ),
        migrations.CreateModel(
            name='Tegirmon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Omborlar',
            },
        ),
        migrations.CreateModel(
            name='TypeExpanse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeofCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeofProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeofTin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOutlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WheatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilo_1', models.FloatField(default=0)),
                ('kilo_2', models.FloatField(default=0)),
                ('kilo_3', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnAkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stansiya', models.CharField(blank=True, max_length=255, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Accepted')], default=1)),
                ('price', models.FloatField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('total', models.FloatField(default=0)),
                ('num1', models.CharField(blank=True, max_length=255, null=True)),
                ('num2', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clientun')),
                ('ombor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon')),
                ('outlay', models.ManyToManyField(to='home.AktUnOutlay')),
                ('wagons', models.ManyToManyField(to='home.AktUnWagon')),
            ],
            options={
                'verbose_name': 'Un Akt',
                'verbose_name_plural': 'Un Aktlar',
            },
        ),
        migrations.CreateModel(
            name='TurnofCarsofTashkent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('waiting', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Yuklanyapti'), ('3', 'Chiqib ketti'), ('4', 'Bekor qilindi')], max_length=255)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='TurnofCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('waiting', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Yuklanyapti'), ('3', 'Chiqib ketti'), ('4', 'Bekor qilindi')], max_length=255)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='Tinhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=1)),
                ('izoh', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clienttin')),
                ('tegirmon', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.typeoftin')),
            ],
            options={
                'verbose_name': 'Qop tarixi',
                'verbose_name_plural': 'Qop tarixi',
            },
        ),
        migrations.CreateModel(
            name='Tin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField()),
                ('tegirmon', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.typeoftin')),
            ],
            options={
                'verbose_name': 'Qop',
                'verbose_name_plural': 'Qoplar',
            },
        ),
        migrations.CreateModel(
            name='Tarozi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product')),
                ('tegirmon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tegirmon')),
            ],
        ),
        migrations.CreateModel(
            name='StoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'created'), ('2', 'accepted')], max_length=50)),
                ('qopsoni', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('tegirmon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('miqdori', models.FloatField(default=0)),
                ('qob_soni', models.IntegerField(blank=True, default=0, help_text='Auto calculate', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_product', to='home.product')),
                ('tegirmon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(choices=[(1, "Tug'ilgan kun"), (2, 'Bayram va boshqalar')])),
                ('date', models.DateField(blank=True, null=True)),
                ('text', models.TextField(default='')),
                ('active', models.BooleanField(default=False)),
                ('customer', models.ManyToManyField(to='home.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SMSHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('send_count', models.IntegerField(default=0)),
                ('not_send_count', models.IntegerField(default=0)),
                ('smstemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.smstemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Sendedsms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.CharField(max_length=2555)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.client')),
                ('clientun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.clientun')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnedIncomeTinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('izoh', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tegirmon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.typeoftin')),
            ],
            options={
                'verbose_name_plural': 'Kirim bulgan qoplarni qaytarish tarixi',
            },
        ),
        migrations.CreateModel(
            name='ReturnedExpanseTinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('izoh', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tegirmon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.typeoftin')),
            ],
            options={
                'verbose_name_plural': 'Chiqim bulgan qoplarni qaytarish tarixi',
            },
        ),
        migrations.CreateModel(
            name='Return_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('izoh', models.CharField(max_length=255)),
                ('qopsoni', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='returned/')),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'finished')], default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('tegirmon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tegirmon')),
            ],
            options={
                'verbose_name': 'Qaytgan mahsulot',
                'verbose_name_plural': 'Qaytgan mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='ResidualBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('filial', models.CharField(max_length=255)),
                ('manzil', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('saler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qaytuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa_total', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Done')], default=1, max_length=255)),
                ('baskets', models.ManyToManyField(to='home.BasketQaytuv')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qopsoni', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('tegirmon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.typeofproduct'),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hudud', models.IntegerField(choices=[(1, 'Samarqand'), (2, 'Toshkent'), (3, 'Jizzax'), (4, "Afg'on"), (5, 'Navoiy'), (6, 'Qashqadaryo'), (7, 'Surxondaryo'), (8, 'Qoraqalpogiston'), (9, 'Andijon'), (10, 'Buxoro'), (11, 'Fargona'), (12, 'Xorazm'), (13, 'Namangan'), (14, 'Sirdaryo')], default=1)),
                ('soni', models.IntegerField(default=0)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')], default=1)),
                ('sotuvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planlar',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistoryUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('1', 'income'), ('2', 'expance')], max_length=255)),
                ('turi', models.CharField(choices=[('1', 'Bank'), ('2', 'Plastik'), ('3', 'Naqd')], max_length=255)),
                ('currency', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('currency_type', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_shot', models.CharField(blank=True, max_length=255, null=True)),
                ('cash', models.CharField(default='', max_length=255)),
                ('by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('custom_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('1', 'income'), ('2', 'expance')], max_length=255)),
                ('turi', models.CharField(choices=[('1', 'Bank'), ('2', 'Plastik'), ('3', 'Naqd')], max_length=255)),
                ('for_expance', models.BooleanField(default=False)),
                ('currency', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('currency_type', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_shot', models.CharField(blank=True, max_length=255, null=True)),
                ('cash', models.CharField(default='', max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.client')),
                ('clienttin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.clienttin')),
                ('clientun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.clientun')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer')),
                ('kassa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cash')),
                ('qozoq_cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.qozoqcash')),
                ('second_cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.secondcash')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.chiqimsubcategory')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tegirmon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tegirmon'),
        ),
        migrations.CreateModel(
            name='Expanse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('izoh', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('1', 'unpaid'), ('2', 'paid')], default=1, max_length=255)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.chiqimsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExpanceTin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izoh', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('tegirmon', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.typeoftin')),
            ],
            options={
                'verbose_name': 'Chiqim qop',
                'verbose_name_plural': 'Chiqim qoplar',
            },
        ),
        migrations.CreateModel(
            name='ConvertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('to_dollor', models.BooleanField(default=False)),
                ('to_som', models.BooleanField(default=False)),
                ('cash', models.CharField(default='', max_length=255)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('izoh', models.CharField(default='Izoh', max_length=255)),
                ('converter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashConvertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_cash', models.CharField(max_length=255)),
                ('to_cash', models.CharField(max_length=255)),
                ('usd_or_uzs', models.IntegerField(choices=[(1, 'USD'), (2, 'UZS')])),
                ('som', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('comment', models.CharField(default='Kassalar urtasida convert', max_length=255)),
                ('converter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kassalar urtasida convert',
            },
        ),
        migrations.CreateModel(
            name='BunkerOutlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bunker', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bunker')),
            ],
            options={
                'verbose_name': 'BunkerOutlay',
                'verbose_name_plural': 'BunkerOutlays',
            },
        ),
        migrations.AddField(
            model_name='basketqaytuv',
            name='brigada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.brigada'),
        ),
        migrations.AddField(
            model_name='basketqaytuv',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.store'),
        ),
        migrations.AddField(
            model_name='basket',
            name='brigada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.brigada'),
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.store'),
        ),
        migrations.CreateModel(
            name='BaskCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdori', models.FloatField(blank=True, default=0, null=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.basket')),
            ],
        ),
        migrations.CreateModel(
            name='BarcodesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Barcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='AktWagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('brutto_akt', models.IntegerField(default=0)),
                ('tara_akt', models.IntegerField(default=0)),
                ('netto_akt', models.IntegerField(default=0)),
                ('brutto_fakt', models.IntegerField(default=0)),
                ('tara_fakt', models.IntegerField(default=0)),
                ('netto_fakt', models.IntegerField(default=0)),
                ('vl_t', models.FloatField(default=0)),
                ('natura', models.IntegerField(default=0)),
                ('kl_na', models.IntegerField(default=0)),
                ('idk', models.IntegerField(default=0)),
                ('sor_n', models.IntegerField(default=0)),
                ('zerno', models.IntegerField(default=0)),
                ('chn', models.IntegerField(default=0)),
                ('bunker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bunker')),
            ],
            options={
                'verbose_name': 'Akt Wagon',
                'verbose_name_plural': 'Akt Wagonlar',
            },
        ),
        migrations.AddField(
            model_name='aktunwagon',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
        migrations.AddField(
            model_name='aktunoutlay',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.typeoutlay'),
        ),
        migrations.CreateModel(
            name='AktOutlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('1', "To'lanmagan"), ('2', "To'langan")], default=1, max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.typeoutlay')),
            ],
        ),
        migrations.CreateModel(
            name='Akt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stansiya', models.CharField(blank=True, max_length=255, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'accepted')], default=1)),
                ('price', models.FloatField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('total', models.FloatField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.client')),
                ('outlay', models.ManyToManyField(to='home.AktOutlay')),
                ('wagons', models.ManyToManyField(to='home.AktWagon')),
            ],
            options={
                'verbose_name': 'Akt',
                'verbose_name_plural': 'Aktlar',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='tegirmon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tegirmon'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
