# Generated by Django 3.2.4 on 2022-02-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status_turi',
            field=models.IntegerField(choices=[(1, 'Kup miqdorda, kam oladi'), (2, 'Kam miqdorda, kup oladi')], default=2),
        ),
    ]
