# Generated by Django 3.2.4 on 2022-06-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_comment_back'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bunker',
            options={},
        ),
        migrations.RemoveField(
            model_name='bunker',
            name='fakt_neto',
        ),
        migrations.AlterField(
            model_name='product',
            name='type_country',
            field=models.IntegerField(blank=True, choices=[(1, 'uz'), (2, 'kz')], default=0, null=True),
        ),
    ]
