# Generated by Django 3.2.4 on 2022-06-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220615_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunkeroutlay',
            name='bunker',
        ),
    ]
