# Generated by Django 3.2.4 on 2022-02-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customer_hudud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='hudud',
            field=models.IntegerField(choices=[(1, 'Samarqand'), (2, 'Toshkent'), (3, 'Jizzax'), (4, "Afg'on"), (5, 'Navoiy'), (6, 'Qashqadaryo'), (7, 'Surxondaryo'), (8, 'Qoraqalpogiston'), (9, 'Andijon'), (10, 'Buxoro'), (11, 'Fargona'), (12, 'Xorazm'), (13, 'Namangan'), (14, 'Sirdaryo')], default=1),
        ),
    ]
