# Generated by Django 3.2.4 on 2022-06-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_bunkeroutlay_bunker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bunker',
            options={'verbose_name': 'Bunker', 'verbose_name_plural': 'Bunkerlar'},
        ),
        migrations.AddField(
            model_name='bunker',
            name='fakt_neto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bunkeroutlay',
            name='bunker',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bunker'),
        ),
    ]
