# Generated by Django 3.2.4 on 2022-02-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220215_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='kassa',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
