# Generated by Django 3.2.4 on 2022-02-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_kassa_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kassa',
            name='bank_shot',
        ),
    ]
