# Generated by Django 3.2.4 on 2022-02-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_kassa_bank_shot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankShot',
        ),
        migrations.DeleteModel(
            name='Kassa',
        ),
        migrations.AlterModelOptions(
            name='cash',
            options={'verbose_name_plural': 'Kassa'},
        ),
    ]
