# Generated by Django 3.2.4 on 2022-02-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220215_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='naqd_pull_dollor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=155),
        ),
        migrations.AddField(
            model_name='cash',
            name='naqd_pull_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=155),
        ),
    ]
