# Generated by Django 3.2.4 on 2022-02-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220215_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='currency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=155),
        ),
    ]
