# Generated by Django 3.2.4 on 2022-02-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_paymenthistory_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='bank_shot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
