# Generated by Django 3.2.4 on 2022-02-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_bankshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankshots',
            options={'verbose_name_plural': 'Bank shotlari'},
        ),
        migrations.AddField(
            model_name='bankshots',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankshots',
            name='shot_numbers',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
