# Generated by Django 3.2.4 on 2022-02-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20220216_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankshots',
            name='shot_numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
