# Generated by Django 3.2.4 on 2022-02-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_bankshots_shot_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tegirmon',
            options={'verbose_name': 'Ombor', 'verbose_name_plural': 'Omborlar'},
        ),
    ]
