# Generated by Django 3.2.4 on 2022-02-24 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinhistory',
            name='tegirmon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon'),
        ),
    ]
