# Generated by Django 3.2.4 on 2022-02-24 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_tinhistory_tegirmon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tin',
            name='tegirmon',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon'),
        ),
        migrations.AlterField(
            model_name='tinhistory',
            name='tegirmon',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon'),
        ),
    ]
