# Generated by Django 3.2.4 on 2022-02-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20220224_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expancetin',
            name='tegirmon',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon'),
        ),
    ]
