# Generated by Django 3.2.4 on 2022-02-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_expancetin_tegirmon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, default=0, help_text='kg', null=True),
        ),
    ]
