# Generated by Django 3.2.4 on 2022-02-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_bankshots_bank_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expancetin',
            name='izoh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expancetin',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
