# Generated by Django 3.2.4 on 2022-02-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20220226_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='order_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
