# Generated by Django 3.2.4 on 2022-02-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='qob_soni',
            field=models.IntegerField(default=0),
        ),
    ]
