# Generated by Django 3.2.4 on 2022-02-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_customer_hudud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='qob_soni',
            field=models.IntegerField(default=0, help_text='Auto calculate'),
        ),
    ]
