# Generated by Django 3.2.4 on 2022-02-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_store_qob_soni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='limit',
            field=models.IntegerField(blank=True, default=400000, null=True),
        ),
    ]
