# Generated by Django 3.2.4 on 2022-03-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20220301_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankshots',
            options={'verbose_name_plural': 'Bank hisob raqamlar'},
        ),
    ]
