# Generated by Django 3.2.4 on 2022-03-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20220301_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
