# Generated by Django 3.2.4 on 2022-03-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_bankshots_options'),
        ('home', '0038_alter_customer_limit'),
    ]

    operations = [
    ]
