# Generated by Django 3.2.4 on 2022-03-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_merge_20220301_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='converthistory',
            name='to_dollor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='converthistory',
            name='to_som',
            field=models.BooleanField(default=False),
        ),
    ]
