# Generated by Django 3.2.4 on 2022-03-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20220301_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='entered_data',
            new_name='entered_date',
        ),
    ]
