# Generated by Django 3.2.4 on 2022-03-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20220301_1643'),
        ('home', '0041_rename_entered_data_order_entered_date'),
    ]

    operations = [
    ]
