# Generated by Django 3.2.4 on 2022-03-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_store_qob_soni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='qob_soni',
        ),
    ]
