# Generated by Django 3.2.4 on 2022-03-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_secondcash'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
