# Generated by Django 3.2.4 on 2022-03-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_paymenthistory_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
