# Generated by Django 3.2.4 on 2022-03-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_cash_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondcash',
            name='money',
        ),
        migrations.AddField(
            model_name='secondcash',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
