# Generated by Django 3.2.4 on 2022-03-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20220303_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catego',
            new_name='ChiqimCategory',
        ),
    ]
