# Generated by Django 3.2.4 on 2022-03-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_rename_catego_chiqimcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqimcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
