# Generated by Django 3.2.4 on 2022-03-03 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_chiqimcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chiqimcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='chiqimcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='chiqimcategory',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='ChiqimSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chiqimcategory')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
