# Generated by Django 3.2.4 on 2022-03-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_auto_20220303_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chiqimsubcategory',
            options={'verbose_name_plural': 'ChiqimCategory'},
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.chiqimsubcategory'),
        ),
    ]
