# Generated by Django 3.2.4 on 2022-03-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20220303_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expanse',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.chiqimsubcategory'),
        ),
    ]
