# Generated by Django 3.2.4 on 2022-03-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_alter_expanse_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expanse',
            name='type',
        ),
    ]
