# Generated by Django 3.2.4 on 2022-03-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_remove_expanse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expanse',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.chiqimsubcategory'),
        ),
    ]
