# Generated by Django 3.2.4 on 2022-03-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QozoqCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naqd_pull_sum', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('naqd_pull_dollor', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Qozoq Kassa',
            },
        ),
    ]
