# Generated by Django 3.2.4 on 2022-03-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_qozoqcash'),
    ]

    operations = [
        migrations.AddField(
            model_name='converthistory',
            name='cash',
            field=models.CharField(default='', max_length=255),
        ),
    ]
