# Generated by Django 3.2.4 on 2022-03-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_converthistory_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qozoqcash',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='secondcash',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
