# Generated by Django 3.2.4 on 2022-03-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_auto_20220305_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='cash',
            field=models.CharField(default='', max_length=255),
        ),
    ]
