# Generated by Django 3.2.4 on 2022-03-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_paymenthistory_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashConvertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_cash', models.CharField(max_length=255)),
                ('to_cash', models.CharField(max_length=255)),
                ('usd_or_uzs', models.IntegerField(choices=[(1, 'USD'), (2, 'UZS')])),
                ('som', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('comment', models.CharField(default='Kassalar urtasida convert', max_length=255)),
            ],
        ),
    ]
