# Generated by Django 3.2.4 on 2022-03-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_cashconverthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashconverthistory',
            options={'verbose_name_plural': 'Kassalar urtasida convert'},
        ),
    ]
