# Generated by Django 3.2.4 on 2022-03-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_alter_cashconverthistory_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='converthistory',
            old_name='cash',
            new_name='from_cash',
        ),
        migrations.AddField(
            model_name='converthistory',
            name='to_cash',
            field=models.CharField(default='', max_length=255),
        ),
    ]
