# Generated by Django 3.2.4 on 2022-03-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_alter_converthistory_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converthistory',
            name='currency',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
