# Generated by Django 3.2.4 on 2022-03-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_alter_converthistory_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converthistory',
            name='dollor',
        ),
        migrations.AlterField(
            model_name='converthistory',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
