# Generated by Django 3.2.4 on 2022-03-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_auto_20220307_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converthistory',
            name='currency',
        ),
        migrations.AddField(
            model_name='converthistory',
            name='izoh',
            field=models.CharField(default='Izoh', max_length=255),
        ),
    ]
