# Generated by Django 3.2.4 on 2022-03-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_auto_20220307_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='miqdori',
            field=models.FloatField(default=0),
        ),
    ]
