# Generated by Django 3.2.4 on 2022-03-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_alter_baskcounter_miqdori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baskcounter',
            name='miqdori',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
