# Generated by Django 3.2.4 on 2022-03-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_alter_baskcounter_miqdori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_product', to='home.product'),
        ),
    ]
