# Generated by Django 3.2.4 on 2022-03-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_alter_store_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='converthistory',
            old_name='from_cash',
            new_name='cash',
        ),
        migrations.RemoveField(
            model_name='converthistory',
            name='to_cash',
        ),
    ]
