# Generated by Django 3.2.4 on 2022-03-11 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_auto_20220311_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashconverthistory',
            name='converter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
