# Generated by Django 3.2.4 on 2022-03-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_cashconverthistory_converter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chiqimcategory',
            options={'verbose_name_plural': 'Chiqim Category'},
        ),
        migrations.AlterModelOptions(
            name='chiqimsubcategory',
            options={'verbose_name_plural': 'Chiqim Sub-Category'},
        ),
    ]
