# Generated by Django 3.2.4 on 2022-03-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_returnedincometinhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnedincometinhistory',
            options={'verbose_name_plural': 'Kirim bugan qoplarni qaytarish tarixi'},
        ),
    ]
