# Generated by Django 3.2.4 on 2022-03-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_alter_returnedincometinhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tin',
            options={'verbose_name': 'Qop', 'verbose_name_plural': 'Qoplar'},
        ),
    ]
