# Generated by Django 3.2.4 on 2022-03-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_alter_tin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedincometinhistory',
            name='tegirmon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon'),
        ),
        migrations.AlterField(
            model_name='returnedincometinhistory',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
