# Generated by Django 3.2.4 on 2022-03-12 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_auto_20220312_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnedincometinhistory',
            options={'verbose_name_plural': 'Kirim bulgan qoplarni qaytarish tarixi'},
        ),
        migrations.CreateModel(
            name='ReturnedExpanseTinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('izoh', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tegirmon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tegirmon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.typeoftin')),
            ],
            options={
                'verbose_name_plural': 'Chiqim bulgan qoplarni qaytarish tarixi',
            },
        ),
    ]
