# Generated by Django 3.2.4 on 2022-03-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_alter_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmborCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('naqd_pull_sum', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('naqd_pull_dollor', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ombor Kassasi',
            },
        ),
    ]
