# Generated by Django 3.2.4 on 2022-03-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_omborcash'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='custom_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
