# Generated by Django 3.2.4 on 2022-03-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_paymenthistory_custom_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akt',
            options={'verbose_name': 'Akt', 'verbose_name_plural': 'Aktlar'},
        ),
        migrations.AlterModelOptions(
            name='aktunwagon',
            options={'verbose_name': 'Akt Un Wagon', 'verbose_name_plural': 'Akts Un Wagonlar'},
        ),
        migrations.AlterModelOptions(
            name='aktwagon',
            options={'verbose_name': 'Akt Wagon', 'verbose_name_plural': 'Akt Wagonlar'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Klint', 'verbose_name_plural': 'Klintlar'},
        ),
        migrations.AlterModelOptions(
            name='clienttin',
            options={'verbose_name': 'Qob klinti', 'verbose_name_plural': 'Qob klintilar'},
        ),
        migrations.AlterModelOptions(
            name='clientun',
            options={'verbose_name': 'Un klinti', 'verbose_name_plural': 'Un klintilar'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Ishchi', 'verbose_name_plural': 'Ishchilar'},
        ),
        migrations.AlterModelOptions(
            name='expancetin',
            options={'verbose_name': 'Chiqim qop', 'verbose_name_plural': 'Chiqim qoplar'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Planlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='return_product',
            options={'verbose_name': 'Qaytgan mahsulot', 'verbose_name_plural': 'Qaytgan mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.AlterModelOptions(
            name='tinhistory',
            options={'verbose_name': 'Qop tarixi', 'verbose_name_plural': 'Qop tarixi'},
        ),
        migrations.AlterModelOptions(
            name='unakt',
            options={'verbose_name': 'Un Akt', 'verbose_name_plural': 'Un Aktlar'},
        ),
    ]
