# Generated by Django 3.2.4 on 2022-03-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_auto_20220325_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
    ]
