# Generated by Django 3.2.4 on 2022-03-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_order_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnofcars',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Yuklanyapti'), ('3', 'Chiqib ketti'), ('4', 'Bekor qilindi')], max_length=255),
        ),
        migrations.AlterField(
            model_name='turnofcarsoftashkent',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Yuklanyapti'), ('3', 'Chiqib ketti'), ('4', 'Bekor qilindi')], max_length=255),
        ),
    ]
