# Generated by Django 3.2.4 on 2022-03-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_alter_order_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='qob_soni',
            field=models.IntegerField(blank=True, default=0, help_text='Auto calculate', null=True),
        ),
    ]
