# Generated by Django 3.2.4 on 2022-03-31 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_store_qob_soni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Maxsulot', 'verbose_name_plural': 'Maxsulotlar'},
        ),
    ]
