# Generated by Django 3.2.4 on 2022-04-08 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_alter_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='kassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cash'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='qozoq_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.qozoqcash'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='second_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.secondcash'),
        ),
    ]
