# Generated by Django 3.2.4 on 2022-04-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_auto_20220420_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankshots',
            name='shot_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
