# Generated by Django 3.2.4 on 2022-05-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_order_date_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_payment',
            field=models.DateField(blank=True, default=True, null=True),
        ),
    ]
