# Generated by Django 3.2.4 on 2022-05-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0103_alter_order_date_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_payment',
        ),
    ]
