# Generated by Django 3.2.4 on 2022-05-25 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0104_remove_order_date_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bunker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Bunker',
                'verbose_name_plural': 'Bunkerlar',
            },
        ),
        migrations.AddField(
            model_name='aktwagon',
            name='chn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aktwagon',
            name='idk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aktwagon',
            name='kl_na',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aktwagon',
            name='natura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aktwagon',
            name='sor_n',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aktwagon',
            name='vl_t',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aktwagon',
            name='zerno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aktwagon',
            name='bunker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bunker'),
        ),
    ]
