# Generated by Django 3.2.4 on 2022-05-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0104_remove_order_date_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='send_sms',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
