# Generated by Django 3.2.4 on 2022-05-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0105_auto_20220525_1815'),
        ('home', '0105_order_return_date'),
    ]

    operations = [
    ]
