# Generated by Django 3.2.4 on 2022-05-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0105_order_send_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='send_sms',
        ),
    ]
