# Generated by Django 3.2.4 on 2022-05-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0106_merge_0105_auto_20220525_1815_0105_order_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktwagon',
            name='bunker',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bunker'),
        ),
    ]
