# Generated by Django 3.2.4 on 2022-05-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0108_merge_0105_auto_20220525_1815_0107_order_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='debt',
            new_name='debt_kz',
        ),
        migrations.AddField(
            model_name='customer',
            name='debt_uz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=155),
        ),
    ]
