# Generated by Django 3.2.4 on 2022-05-31 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0108_bunker_fakt_neto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BunkerOutlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.ImageField(default=0, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bunker', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bunker')),
            ],
            options={
                'verbose_name': 'BunkerOutlay',
                'verbose_name_plural': 'BunkerOutlays',
            },
        ),
    ]
