# Generated by Django 3.2.4 on 2022-05-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0109_bunkeroutlay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunkeroutlay',
            name='miqdor',
            field=models.IntegerField(default=0),
        ),
    ]
