# Generated by Django 3.2.4 on 2022-06-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0109_auto_20220531_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='summa_total_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=155),
        ),
    ]
