# Generated by Django 3.2.4 on 2022-06-04 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0112_auto_20220604_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='city',
        ),
        migrations.AddField(
            model_name='plan',
            name='hudud',
            field=models.IntegerField(choices=[(1, 'Samarqand'), (2, 'Toshkent'), (3, 'Jizzax'), (4, "Afg'on"), (5, 'Navoiy'), (6, 'Qashqadaryo'), (7, 'Surxondaryo'), (8, 'Qoraqalpogiston'), (9, 'Andijon'), (10, 'Buxoro'), (11, 'Fargona'), (12, 'Xorazm'), (13, 'Namangan'), (14, 'Sirdaryo')], default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='sotuvchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
