# Generated by Django 3.2.4 on 2022-06-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0108_bunker_fakt_neto'),
        ('home', '0113_auto_20220604_1530'),
    ]

    operations = [
    ]
