# Generated by Django 3.2.4 on 2022-06-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0112_alter_employee_type'),
        ('home', '0114_merge_0108_bunker_fakt_neto_0113_auto_20220604_1530'),
    ]

    operations = [
    ]
