# Generated by Django 3.2.4 on 2022-06-07 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0115_merge_20220606_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeofCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='bunker',
            name='fakt_neto',
        ),
        migrations.AlterField(
            model_name='aktwagon',
            name='bunker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bunker'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sotuvchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='type_country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.typeofcountry'),
            preserve_default=False,
        ),
    ]
