# Generated by Django 3.2.4 on 2022-06-07 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0116_auto_20220607_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.typeofcountry'),
        ),
    ]
