# Generated by Django 3.2.4 on 2022-06-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0116_auto_20220606_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunker',
            name='fakt_neto',
            field=models.IntegerField(default=0),
        ),
    ]
