# Generated by Django 3.2.4 on 2022-06-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0117_bunker_fakt_neto'),
        ('home', '0118_alter_product_type_country'),
    ]

    operations = [
    ]
